# Generated by Django 4.1.3 on 2023-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
