# Generated by Django 4.1.3 on 2023-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
