# Generated by Django 4.1.3 on 2023-03-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='memo',
        ),
    ]
