# Generated by Django 4.1.3 on 2023-05-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_by',
        ),
    ]
