# Generated by Django 4.1.3 on 2023-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comments_comment_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
